namespace chip {
namespace fuzzing {
#define CHIP_FUZZER_ERROR_INITIALIZATION_FAILED CHIP_APPLICATION_ERROR(0x01)
#define CHIP_FUZZER_ERROR_NOT_FOUND CHIP_APPLICATION_ERROR(0x02)
#define CHIP_FUZZER_ERROR_NOT_IMPLEMENTED CHIP_APPLICATION_ERROR(0x03)
#define CHIP_FUZZER_ERROR_NODE_SCAN_FAILED CHIP_APPLICATION_ERROR(0x04)
#define CHIP_FUZZER_FILESYSTEM_ERROR CHIP_APPLICATION_ERROR(0x05)
#define CHIP_FUZZER_UNEXPECTED_ERROR CHIP_APPLICATION_ERROR(0x06)
#define CHIP_FUZZER_GENERIC_ERROR CHIP_APPLICATION_ERROR(0x07)
} // namespace fuzzing
} // namespace chip
